disabled_rules:
  - force_cast

included:
  # Target name that you want to include
  - SingSong

excluded:
  # If you use R.swift, required excluding R.generated.swift file.
  # Descript the path.
  - PROJECT_NAME/R.generated.swift
  
  
# Rules

line_length: 500
large_tuple: 5

file_length:
  warning: 500
  error: 1200

nesting:
  type_level:
    warning: 2

identifier_name:
    max_length:
      warning: 45
      error: 60
    min_length:
      warning: 2
      error: 1
    excluded:
      - id
      - URL
    
cyclomatic_complexity: 20

    
